config/routes.rb
Rails.application.routes.draw do

  resources :words
  resources :profiles, only: [:index, :show, :create, :new]
  resources :companies

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :profiles
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  belongs_to :company
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :profiles
  validates :document, presence: true
end

app/models/word.rb
class Word < ApplicationRecord
  validates :name, presence:true
  validates :d_value, presence:true
  validates :i_value, presence:true
  validates :s_value, presence:true
  validates :c_value, presence:true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
       devise_parameter_sanitizer.permit(:sign_up, keys: [:document])
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
    skip_before_action :authenticate_user!, only: [:index, :show]


  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    @company.save
    redirect_to company_path(@company)
  end

  def update
    @company.update(company_params)
    redirect_to company_path(@company)
  end

  def edit
    @company.save
    redirect_to company_path(@company)
  end

  def destroy
    @company.destroy
    redirect_to companies_path
  end

  def index
    @companies = Company.all
  end

  def show
  end

  private

  def company_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:company).permit(:name, :document, :allowed_domains)
  end

  def set_company
    @company = Company.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    if @profile.save
      redirect_to profiles_path
    else
      render :new
    end
  end

  private

  def profile_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:profile).permit(:d_value, :i_value, :s_value, :c_value, :user_id, :company_id)
  end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.all
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:name, :d_value, :i_value, :s_value, :c_value)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/_form.html.erb
<%= form_for(company) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :document %>
    <%= f.text_field :document, class: 'form-control' %>
  </div>

   <div class="form-group">
    <%= f.label :allowed_domains %>
    <%= f.text_field :allowed_domains, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/companies/edit.html.erb
<%= render 'form', company: @company %>

app/views/companies/index.html.erb
<div class="container">
  <h1>Companies</h1>
  <p>List of all companies</p>
  <!-- app/views/restaurants/index.html.erb -->
  <% @companies.each do |company| %>
  <p>
    <%= link_to company.name, company_path(company) %>
  </p>
  <% end %>
  <%= link_to "New Company", new_company_path  %>
</div>

app/views/companies/new.html.erb
<%= render 'form', company: @company %>

app/views/companies/show.html.erb
<div class="container">
  <h1><%= @company.name %></h1>
  <!-- app/views/restaurants/show.html.erb -->
  <p>Document = <%= @company.document %></p>
  <p>Allowed domains = <%= @company.allowed_domains %></p>

  <%= link_to "Delete", company_path(@company),
  method: :delete,
  data: { confirm: "Are you sure?" } %>
  <%= link_to "Back", :back  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Home</h1>
<% if user_signed_in? %>
<%= link_to "New Exam", new_profile_path %>
<% end %>

app/views/profiles/_form.html.erb
<div class="container">
  <div class="form-inputs">
    <%= simple_form_for @profile do |f| %>
    <%= f.input :d_value, :label => "Value D", required: true %>
    <%= f.input :i_value, :label => "Value I", required: true  %>
    <%= f.input :s_value, :label => "Value S", required: true %>
    <%= f.input :c_value, :label => "Value C", required: true %>
    <%= f.association :company, :label => "Select company", required: true %>
    <div class="form-actions">
      <%= f.button :submit, "Send", class: "btn-primary" %>
    </div>
    <% end %>
  </div>
</div>

app/views/profiles/index.html.erb
<div class="container">
  <h1>Profiles</h1>
  <p>List of all profiles</p>

  <% @profiles.each do |profile| %>
  <p>
    <%= link_to profile.user.email, profile_path(profile) %>
  </p>
  <% end %>
</div>

app/views/profiles/new.html.erb
<%= render 'form', profile: @profile %>

app/views/profiles/show.html.erb
<div class="container">
  <h1><%= @profile.user.email %></h1>
  <p>D = <%= @profile.d_value %></p>
  <p>I = <%= @profile.i_value %></p>
  <p>S = <%= @profile.s_value %></p>
  <p>C = <%= @profile.c_value %></p>
  <p>Company = <%= @profile.company.name %></p>
  <%= link_to "Back", :back  %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/words/_form.html.erb
<%= simple_form_for(@word) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :d_value %>
    <%= f.input :i_value %>
    <%= f.input :s_value %>
    <%= f.input :c_value %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Words</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>D value</th>
        <th>I value</th>
        <th>S value</th>
        <th>C value</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @words.each do |word| %>
      <tr>
        <td><%= word.name %></td>
        <td><%= word.d_value %></td>
        <td><%= word.i_value %></td>
        <td><%= word.s_value %></td>
        <td><%= word.c_value %></td>
        <td><%= link_to 'Show', word %></td>
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Word', new_word_path %>
</div>

app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @word.name %>
</p>

<p>
  <strong>D value:</strong>
  <%= @word.d_value %>
</p>

<p>
  <strong>I value:</strong>
  <%= @word.i_value %>
</p>

<p>
  <strong>S value:</strong>
  <%= @word.s_value %>
</p>

<p>
  <strong>C value:</strong>
  <%= @word.c_value %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>